# IMPORTING LIBRARIES

In [1]:
import pandas as pd

# LOADING DATA

In [2]:
ep=pd.read_csv("Employee_Performance.csv")

In [3]:
ep.head()

,Employee_ID,Department,Experience (Years),Education_Level,Monthly_Salary,Performance_Score
0,dd919c23,IT,5,PhD,7460,5
1,c78cc3c2,HR,23,PhD,13215,8
2,253fabaf,HR,25,PhD,6230,4
3,1995c696,Finance,16,Master's,8005,8
4,119f29d6,Finance,27,Master's,8226,7

# CHECKING DATA FOR NULL VALUE

In [4]:
ep.isnull().sum()

Employee_ID           0
Department            0
Experience (Years)    0
Education_Level       0
Monthly_Salary        0
Performance_Score     0
dtype: int64

# TOP 10 PRODUCTIVE EMPLOYEE-BASED ON PERFORMANCE

In [5]:
PRODUCTIVITY_PORFOR = ep['Performance_Score'] / ep['Monthly_Salary'] * 10000
PRODUCTIVITY_PORFOR = pd.DataFrame({
    'Employee_ID': ep['Employee_ID'],
    'Productivity': PRODUCTIVITY_PORFOR
})
PRODUCTIVITY_PORFOR = PRODUCTIVITY_PORFOR.sort_values(by='Productivity', ascending=False)
PRODUCTIVITY_PORFOR.head(10)

   Employee_ID  Productivity
16    8ef21b1d     22.096735
59    0d009c5c     21.645022
6     3c427a4d     21.221410
50    4850e9e1     19.523624
27    91230120     18.674136
57    cd303546     17.355085
20    9a5ecbfc     17.142857
30    e6fdd1f3     16.160310
91    d8e7e987     15.093074
9     c12a82d7     14.929830

# 10 LEAST PRODUCTIVE EMPLOYEE BASED ON PERFORMANCE

In [6]:
PRODUCTIVITY_PORFOR = PRODUCTIVITY_PORFOR.sort_values(by='Productivity', ascending=True)
PRODUCTIVITY_PORFOR.head(10)

   Employee_ID  Productivity
12    dcd08e41      0.687947
19    3e4c6cc3      0.807103
21    b4f883bc      0.825423
43    1a2ea309      0.880359
10    bee3a60e      0.907688
89    66fa7450      0.914997
94    444b8406      0.922850
45    0608518a      1.069061
51    929579ca      1.152472
84    f5adc5ce      1.247661

# TOP 10 PRODUCTIV EMPLOYEE PRODUCTIVITY BASE ON EXPERIENCE

In [7]:
PRODUCTIVITY_EXP=ep['Performance_Score']/ep['Experience (Years)']
PRODUCTIVITY_EXP = pd.DataFrame({
    'Employee_ID': ep['Employee_ID'],
    'Productivity_Exp': PRODUCTIVITY_EXP
})
PRODUCTIVITY_EXP.sort_values(by='Productivity_Exp',ascending=False).head(10)

   Employee_ID  Productivity_Exp
55    c7e4c4aa               inf
16    8ef21b1d          9.000000
75    581c6ad5          7.000000
60    e51bb910          5.000000
92    88f87782          3.500000
57    cd303546          3.333333
99    eae62914          2.250000
54    a4ce916c          2.000000
96    47b8d43e          1.600000
73    2420f6a5          1.285714

# 10 LEAST PRODUCTIVE EMPLOYEE BASED ON EXPERIENCE

In [8]:
PRODUCTIVITY_EXP.sort_values(by='Productivity_Exp',ascending=True).head(10)

   Employee_ID  Productivity_Exp
47    4586b73e          0.040000
10    bee3a60e          0.045455
43    1a2ea309          0.045455
12    dcd08e41          0.047619
46    bf34701d          0.050000
70    e742d4e7          0.050000
84    f5adc5ce          0.052632
8     5a408619          0.071429
5     c476abfd          0.086957
51    929579ca          0.090909

# TOP 10 PRODUCTIVE EMPLOYEE BASED ON SALARY

In [9]:
Productivity_Salary = ep[['Employee_ID', 'Performance_Score', 'Monthly_Salary']].copy()
Productivity_Salary['Productivity_on_salary'] = (
    Productivity_Salary['Performance_Score'] /
    Productivity_Salary['Monthly_Salary']
) * 1000
Productivity_Salary = Productivity_Salary.sort_values(
    by='Productivity_on_salary',
    ascending=False
)
Productivity_Salary.drop(columns=['Performance_Score','Monthly_Salary']).head(10)

   Employee_ID  Productivity_on_salary
16    8ef21b1d                2.209673
59    0d009c5c                2.164502
6     3c427a4d                2.122141
50    4850e9e1                1.952362
27    91230120                1.867414
57    cd303546                1.735509
20    9a5ecbfc                1.714286
30    e6fdd1f3                1.616031
91    d8e7e987                1.509307
9     c12a82d7                1.492983

# LEAST 10 PRODUCTIVE EMPLOYEE ON SALARY BASED

In [10]:
Productivity_Salary = Productivity_Salary.sort_values(
    by='Productivity_on_salary',
    ascending=True
)
Productivity_Salary.drop(columns=['Performance_Score','Monthly_Salary']).head(10)

   Employee_ID  Productivity_on_salary
12    dcd08e41                0.068795
19    3e4c6cc3                0.080710
21    b4f883bc                0.082542
43    1a2ea309                0.088036
10    bee3a60e                0.090769
89    66fa7450                0.091500
94    444b8406                0.092285
45    0608518a                0.106906
51    929579ca                0.115247
84    f5adc5ce                0.124766

# TOP 10 PRODUCTIVE EMPLOYEES ON DEPARTMENT BASED

In [11]:
Department_productivity = pd.DataFrame({
    'Employee_ID': ep['Employee_ID'],
    'Department': ep['Department'],
    'Monthly_Salary': ep['Monthly_Salary'],
    'Productivity_on_salary': Productivity_Salary['Productivity_on_salary']
})
Department_productivity.sort_values(by='Productivity_on_salary',ascending=False).head(10)

   Employee_ID Department  Monthly_Salary  Productivity_on_salary
16    8ef21b1d    Finance            4073                2.209673
59    0d009c5c         HR            3234                2.164502
6     3c427a4d    Finance            4241                2.122141
50    4850e9e1         HR            5122                1.952362
27    91230120    Finance            4284                1.867414
57    cd303546      Sales            5762                1.735509
20    9a5ecbfc      Sales            3500                1.714286
30    e6fdd1f3         IT            6188                1.616031
91    d8e7e987         HR            5963                1.509307
9     c12a82d7      Sales            3349                1.492983

# LAEST 10 PRODUCTIVE EMPLOYEES ON DEPARTMENT BASED

In [12]:
Department_productivity.sort_values(by='Productivity_on_salary',ascending=True).head(10)

   Employee_ID Department  Monthly_Salary  Productivity_on_salary
12    dcd08e41         HR           14536                0.068795
19    3e4c6cc3      Sales           12390                0.080710
21    b4f883bc         HR           12115                0.082542
43    1a2ea309         HR           11359                0.088036
10    bee3a60e         IT           11017                0.090769
89    66fa7450      Sales           10929                0.091500
94    444b8406    Finance           10836                0.092285
45    0608518a      Sales            9354                0.106906
51    929579ca         HR            8677                0.115247
84    f5adc5ce    Finance            8015                0.124766