# importing Libraries

In [1]:
import pandas as pd

In [2]:
fb=pd.read_csv(r"Social-media-dataset-samples-main\Facebook-datasets.csv")
ig=pd.read_csv(r"Social-media-dataset-samples-main\Instagram-datasets.csv")
tt=pd.read_csv(r"Social-media-dataset-samples-main\TikTok-datasets.csv")
tw=pd.read_csv(r"Social-media-dataset-samples-main\Twitter- datasets.csv")

# ADDING A PLATFORM COLUMN IN DATASET

In [3]:
fb['Platform'] = 'Facebook'
ig['Platform'] = 'Instagram'
tt['Platform'] = 'TikTok'
tw['Platform'] = 'Twitter'

# COMBINING ALL DATASET IN ONE:

In [4]:
df = pd.concat([fb, ig, tt, tw], ignore_index=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 56 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   url                      4000 non-null   object
 1   post_id                  3000 non-null   object
 2   post_url                 3000 non-null   object
 3   comment_id               3000 non-null   object
 4   user_name                1000 non-null   object
 5   user_id                  1000 non-null   object
 6   user_url                 408 non-null    object
 7   date_created             2000 non-null   object
 8   comment_text             1964 non-null   object
 9   num_likes                1000 non-null   float64
 10  num_replies              1398 non-null   float64
 11  attached_files           90 non-null     object
 12  video_length             0 non-null      float64
 13  source_type              964 non-null    object
 14  subtype                  964 non-null    object
 15  type                     1000 non-null   object
 16  Platform                 4000 non-null   object
 17  comment_user             1000 non-null   object
 18  comment_user_url         1000 non-null   object
 19  comment_date             1000 non-null   object
 20  comment                  1000 non-null   object
 21  likes_number             1000 non-null   float64
 22  replies_number           1000 non-null   float64
 23  replies                  1998 non-null   object
 24  hashtag_comment          6 non-null      object
 25  tagged_users_in_comment  146 non-null    object
 26  post_user                1000 non-null   object
 27  post_date_created        1000 non-null   object
 28  commenter_user_name      1000 non-null   object
 29  commenter_id             1000 non-null   float64
 30  commenter_url            1000 non-null   object
 31  comment_url              1000 non-null   object
 32  id                       1000 non-null   float64
 33  user_posted              1000 non-null   object
 34  name                     1000 non-null   object
 35  description              1000 non-null   object
 36  date_posted              1000 non-null   object
 37  photos                   456 non-null    object
 38  tagged_users             374 non-null    object
 39  reposts                  1000 non-null   float64
 40  likes                    1000 non-null   float64
 41  views                    1000 non-null   float64
 42  external_url             432 non-null    object
 43  hashtags                 572 non-null    object
 44  followers                1000 non-null   float64
 45  biography                997 non-null    object
 46  posts_count              1000 non-null   float64
 47  profile_image_link       1000 non-null   object
 48  following                1000 non-null   float64
 49  is_verified              1000 non-null   object
 50  quotes                   1000 non-null   float64
 51  bookmarks                1000 non-null   float64
 52  parent_post_details      1000 non-null   object
 53  external_image_urls      208 non-null    object
 54  videos                   306 non-null    object
 55  quoted_post              1000 non-null   object
dtypes: float64(15), object(41)
memory usage: 1.7+ MB

In [5]:
df.isnull().sum()

url                           0
post_id                    1000
post_url                   1000
comment_id                 1000
user_name                  3000
user_id                    3000
user_url                   3592
date_created               2000
comment_text               2036
num_likes                  3000
num_replies                2602
attached_files             3910
video_length               4000
source_type                3036
subtype                    3036
type                       3000
Platform                      0
comment_user               3000
comment_user_url           3000
comment_date               3000
comment                    3000
likes_number               3000
replies_number             3000
replies                    2002
hashtag_comment            3994
tagged_users_in_comment    3854
post_user                  3000
post_date_created          3000
commenter_user_name        3000
commenter_id               3000
commenter_url              3000
comment_url                3000
id                         3000
user_posted                3000
name                       3000
description                3000
date_posted                3000
photos                     3544
tagged_users               3626
reposts                    3000
likes                      3000
views                      3000
external_url               3568
hashtags                   3428
followers                  3000
biography                  3003
posts_count                3000
profile_image_link         3000
following                  3000
is_verified                3000
quotes                     3000
bookmarks                  3000
parent_post_details        3000
external_image_urls        3792
videos                     3694
quoted_post                3000
dtype: int64

In [6]:
df=df.drop(columns = ['url', 'post_url', 'user_url', 'comment_user_url', 'commenter_url', 'comment_url','external_url', 'external_image_urls', 'profile_image_link', 'parent_post_details',
    'attached_files', 'source_type', 'biography', 'name', 'id', 'videos', 'photos', 'hashtags', 'tagged_users', 'quotes', 'bookmarks', 'description'])
df.head()

,post_id,comment_id,user_name,user_id,date_created,comment_text,num_likes,num_replies,video_length,subtype,...,user_posted,date_posted,reposts,likes,views,followers,posts_count,following,is_verified,quoted_post
0,pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...,Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTA2NTc0NzI3Nj...,Kat███Dav███on,pfbid02QbSc7Zs4wR67DWEXtcGGyDdP6MjktDUBe7MHb2b...,"""2024-01-12T13:41:08.000Z""",Joy House,NaN,1.0,NaN,TextWithEntities,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...,Y29tbWVudDozOTczNzM0OTkzNDQxNDNfMzE2MjYyOTc0Nz...,Jam███McI███re,pfbid02DAD4uXif7L2ibVx7zZ4B8vbza7Tqrqzdn1kF3T1...,"""2024-01-19T22:33:51.000Z""",Yet if a Verizon customer travels outside of t...,NaN,1.0,NaN,TextWithEntities,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...,Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTE0MTkxMTI2Nz...,Bub███Bug███,pfbid02DVKaLESKQqoYHcmo2HeMBuUs2JNK18KZDMa1hML...,"""2024-01-16T01:39:54.000Z""",Where is the 5g we was promised 2 years ago,NaN,1.0,NaN,TextWithEntities,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,260478723678355,Y29tbWVudDo3NTY0MDE0ODY1MjY5MTJfMTA3NDgyMzY5Mz...,Dan███uth███,pfbid0WfY4JxPXbR2Xp4tsUCaaVtwGqwArAbCEL3BM7QXS...,"""2024-02-06T02:46:19.000Z""",Your customer service may be the worst on eart...,NaN,1.0,NaN,TextWithEntities,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,pfbid02dTZDs29765oxhxyV6s3Pmzeq2H8XPEeiCdaZiAj...,Y29tbWVudDo4NjcyMzM5MzU1NzMzMjNfNTUwNjE4MzI3Nz...,Mus███Ali███nne███,100004055062562,"""2024-11-28T08:40:43.000Z""",And what does this picture suppose to mean? Th...,NaN,1.0,NaN,TextWithEntities,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   post_id                  3000 non-null   object
 1   comment_id               3000 non-null   object
 2   user_name                1000 non-null   object
 3   user_id                  1000 non-null   object
 4   date_created             2000 non-null   object
 5   comment_text             1964 non-null   object
 6   num_likes                1000 non-null   float64
 7   num_replies              1398 non-null   float64
 8   video_length             0 non-null      float64
 9   subtype                  964 non-null    object
 10  type                     1000 non-null   object
 11  Platform                 4000 non-null   object
 12  comment_user             1000 non-null   object
 13  comment_date             1000 non-null   object
 14  comment                  1000 non-null   object
 15  likes_number             1000 non-null   float64
 16  replies_number           1000 non-null   float64
 17  replies                  1998 non-null   object
 18  hashtag_comment          6 non-null      object
 19  tagged_users_in_comment  146 non-null    object
 20  post_user                1000 non-null   object
 21  post_date_created        1000 non-null   object
 22  commenter_user_name      1000 non-null   object
 23  commenter_id             1000 non-null   float64
 24  user_posted              1000 non-null   object
 25  date_posted              1000 non-null   object
 26  reposts                  1000 non-null   float64
 27  likes                    1000 non-null   float64
 28  views                    1000 non-null   float64
 29  followers                1000 non-null   float64
 30  posts_count              1000 non-null   float64
 31  following                1000 non-null   float64
 32  is_verified              1000 non-null   object
 33  quoted_post              1000 non-null   object
dtypes: float64(12), object(22)
memory usage: 1.0+ MB

# CALCULATING ENGAGEMENT

## COUNTING REPLIES AND COMMENTS

In [8]:
df['comment_count'] = df['comment'].notna().astype(int)
df['reply_count'] = df['replies'].notna().astype(int)

# CALCULATING TOTAL ENGAGEMENT

In [9]:
df['Total_Engagement'] = (
    df[['likes', 'reposts', 'views',
        'num_likes', 'likes_number',
        'num_replies', 'replies_number']]
    .fillna(0)
    .sum(axis=1)
    + df['comment_count']
    + df['reply_count']
)
df.groupby('Platform')['Total_Engagement'].sum().sort_values(ascending=False)

Platform
Twitter      269174602.0
Instagram         6899.0
TikTok            3252.0
Facebook          1079.0
Name: Total_Engagement, dtype: float64

# POST PASTING PATTERN BY PLATFORM

In [14]:
df.groupby('Platform').agg(
    total_posts=('post_id', 'count'),
    avg_engagement=('Total_Engagement', 'mean')
).sort_index(ascending=False)

           total_posts  avg_engagement
Platform
Twitter              0      269174.602
TikTok            1000           3.252
Instagram         1000           6.899
Facebook          1000           1.079